config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  'static_pages#home'
  get       '/signup',    to: 'users#new'
  post      '/signup',    to: 'users#create'
  get       '/login',     to: 'sessions#new'
  post      '/login',     to: 'sessions#create'
  delete    '/logout',    to: 'sessions#destroy'
  resources :users
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendences, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendences, source: :attendee

  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }
end

app/models/event_attendence.rb
class EventAttendence < ApplicationRecord
  belongs_to :attended_event, class_name: "Event"
  belongs_to :attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_attendences, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendences


  def upcoming_events
    attended_events.where("date <= :present", {present: Time.now} )
  end

  def previous_events
    attended_events.where("date > :present", {present: Time.now})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only:[:create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if current_user.events << @event
      flash[:success] = "Event Created"
      redirect_to events_path
    else
      flash[:now] = "invalid event info"
      render 'new'
    end
  end

  def event_params
    params.require(:event).permit(:title, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:info] = "invalid credentials"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:now] = "successful sign up"
      redirect_to users_path
    else
      flash[:now] = "bad sign up"
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.user_id
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    logged_in?
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1> All Events </h1>

Past Events
<ul>
  <% @events.past.each do |event| %>
    <li><%= event.title %> @ <%= event.location %> BY <%= User.find_by(id: event.creator_id).name %></li>
  <% end %>
</ul>

<br>

Upcoming Events
<ul>
  <% @events.upcoming.each do |event| %>
    <li><%= event.title %> @ <%= event.location %> BY <%= User.find_by(id: event.creator_id).name %></li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1> Create Event </h1>

<%= form_for @event do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %>

  <%= f.submit "Create Event", class: 'btn btn-primary' %>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %> </h1>
<p>created by <%= User.find_by(id: @event.creator_id).name %> <p> 

<h3> Attendees </h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1> Home </h1>

<% if logged_in? %>
  <p><%= current_user.name %> Logged In! <p>
  <%= button_to "Log Out", logout_path, method: :delete, class: "btn btn-primary" %>
<% end %>

<%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-primary" %>
<%= link_to "Log In", login_path, class: "btn btn-primary" %>

app/views/users/index.html.erb
<h1> All Users </h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> & <%= user.id %></li>
  <% end %>
<ul>

app/views/users/new.html.erb
<h1> Sign Up User </h1>

<%= form_for @user do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.submit "Create Account", class: 'btn btn-primary' %>

<% end %>

app/views/users/show.html.erb
<h1> Show for <%= @user.name %> - user id: <%=@user.id%></h1>

<h3>Upcoming Events</h3>
<ul>
  <% @user.upcoming_events.each do |event| %>
    <li><%= event.title %> @ <%= event.location %> ( <%= event.date %> )</li>
  <% end %>
</ul>

<h3>Previous Events</h3>
<ul>
  <% @user.previous_events.each do |event| %>
    <li><%= event.title %> @ <%= event.location %> ( <%= event.date %> )</li>
  <% end %>
</ul>